language: java
dist: trusty
sudo: false # faster builds

# safelist
branches:
  only:
  - master
  - dev

env:
  global:
    - DEV_BRANCH=dev
    - RELEASE_BRANCH=master
    - REPO=ebx/ebx-cachebase-sdk
    - NO_COLOUR='\033[0m'
    - RED_COLOUR='\033[0;31m'
    - GREEN_COLOUR='\033[0;32m'

before_script:
  - export SOURCE_BRANCH_NAME=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi) 
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import || echo "Failed to import GPG_SECRET_KEYS (probably because this branch is a PR)."
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust || echo "Failed to import GPG_OWNERTRUST (probably because this branch is a PR)."
  - source Infrastructure/Build-Scripts/export_mvn_version.sh
  - source Infrastructure/Build-Scripts/validate_build.sh

script:
  - source Infrastructure/Build-Scripts/build_sdk_travis.sh
  
after_failure:
  - cat target/surefire-reports/*.txt

## Prepare the release for Github
## Ensure we have a suitable git tag for the release based on the verison number
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "MarcFletcher"
  - git config --local user.email "marc@echobox.com"
  - export DEPLOY_TAG=v$MVN_VERSION
  - git tag $DEPLOY_TAG
  
## Create the release in Github
deploy:
  provider: releases
  api_key:
    secure: ForMuu/exBvl3Psj/VW1Q8lI+cS2NO7lbmX0e/NtK9Zr1eMeX4Ey07hxLYtdPcmlzJE8gHLmTDq89IO3sL8OoqeJVsS4aV4O/s/7VKuAcZqekhEE6v1VQe0zGiTXhFdJ6G1PuXxobO6ssV3JPsTD092TklCxebfPVE3YTqyPSGsByNlkdpHIRbbdYcSSu/zE7IVtSGKlKKVAoTIrN1Ydad07aNI5sxgibVlC1xgNI+SDlhjH1W4IciRvDvu2y28xqbeS6NFCAZFE2ySYMofJJreG7RJC1jzJmwWljWH9YPci9wMAfA/COTDNhMqL8vnFtveoOl422B95aNJVCFfLufROIPtbCfuKO5kQAHH4hv4mcix6gqFLW25MGq3zsyyBQfoKkfwsXhKYaHuJ0Lq7WE768Rtl/xTcCmfwjyxQSpmxCb0TGPSTqZ7BL1c6/FqFsgJaLS/V0CVj/fjXqkF5W1N32N2kbr/75kYpApbTizOAiJHPbwt0q5aJ4oeE5XosL2WhErazQikQhEkR+YBB6NeQVTWPvzq3uljPKy/C5rSKLk8vV8i4a/9+sWf3nnRAxppOwvh+vKzi5BN9ZLN/u2+wnF49ZbRSSCTy6Y00jEUhfzg5ZM9TimCKjcFHnv5JZGnpaAqqOIwoImCzbvAm58uj1DGxPtD6yJZD3GlUXKs=
  file: 
    - target/ebx-cachebase-sdk-$MVN_VERSION.jar
    - target/ebx-cachebase-sdk-$MVN_VERSION-javadoc.jar
    - target/ebx-cachebase-sdk-$MVN_VERSION-sources.jar
  edge: true
  on:
    repo: $REPO
    branch: $RELEASE_BRANCH
  name: v$MVN_VERSION
  
cache:
  directories:
    - ~/.m2/repository
