language: java
dist: trusty
sudo: false # faster builds

# safelist
branches:
  only:
  - master
  - dev

env:
  global:
    - DEV_BRANCH=dev
    - RELEASE_BRANCH=master
    - REPO=ebx/ebx-cachebase-sdk
    - NO_COLOUR='\033[0m'
    - RED_COLOUR='\033[0;31m'
    - GREEN_COLOUR='\033[0;32m'

before_script:
  - export SOURCE_BRANCH_NAME=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi) 
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import || echo "Failed to import GPG_SECRET_KEYS (probably because this branch is a PR)."
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust || echo "Failed to import GPG_OWNERTRUST (probably because this branch is a PR)."
  - source Infrastructure/Build-Scripts/export_mvn_version.sh
  - source Infrastructure/Build-Scripts/validate_build.sh

script:
  - source Infrastructure/Build-Scripts/build_sdk_travis.sh
  
after_failure:
  - cat target/surefire-reports/*.txt

## Prepare the release for Github
## Ensure we have a suitable git tag for the release based on the verison number
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "MarcFletcher"
  - git config --local user.email "marc@echobox.com"
  - export DEPLOY_TAG=v$MVN_VERSION
  - git tag $DEPLOY_TAG
  
## Create the release in Github
deploy:
  provider: releases
  api_key:
    secure: pwPS9nHVTGhVFogFbXCtj3gFeRKc9Ph/7ojFp6O3IROzcQ7Qkdy0yWbWAarY5KOhN/oDrTioJBqcJe/oNcXC9WipPuYYR9h3okDw27AN2HxrVrW6xQR3mOQwHEs7geN5m1QTnw/7PILy+MM09506mnoAw/UElsZGEg0RfIXYAupYwu6yOCHZ+evlEZ43GnDkcZ1K/j/mRdXZnUqAL4xWc5Yg+5nUHp808Yroc6p060ih58kpTYlUq45F0ZMoM59tFlensqTh/A6pSQWu9s8KJGO1zS6TGLTbONWyYV2upoAnlYzIe6BCpobOYa7jj/4JwdFubZ8dq09iI1JMnedy4Nv3U2CTCfQQmfn42iVLnr/S9+CmXE2i/RC9BaNCQQ08yY5KKPLaHA4kwwk9cS9ujEZq/GNlPzsPihUU2Umf6kL3o0MTamEE9Y5WBjuH/79rc24hH2JN4tFog2x09D8e8XEE65KkpKd+b3cvjvr2U2bnYvBChqZAUYyXT12gn+3+38ooxpJY5Fw6wPxc4iNAa8h/I0MFbHbAiBgjpHN0xV1LPwvEQIcbguGm2nNggDIwRChGLooBhcTNQNQWUfQwSV9GkAe7cw3kAbUf/AlUKEzeL/GfkUjENz+9JB+fMhnwT5Ryc1b19mYchX3ij9nmr3tvNkwf012V8OoJZbMwW7s=
  file: 
    - target/ebx-cachebase-sdk-$MVN_VERSION.jar
    - target/ebx-cachebase-sdk-$MVN_VERSION-javadoc.jar
    - target/ebx-cachebase-sdk-$MVN_VERSION-sources.jar
  skip_cleanup: true
  on:
    repo: $REPO
    branch: $RELEASE_BRANCH
  name: v$MVN_VERSION
  
cache:
  directories:
    - ~/.m2/repository
